# Generated by Django 6.0.7 on 2026-08-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('order_confirmation', 'Order Confirmation'), ('shipping_update', 'Shipping Update'), ('delivery_update', 'Delivery Update'), ('payment_update', 'Payment Update'), ('password_reset', 'Password Reset'), ('promo', 'Promotional')], max_length=30),
        ),
    ]
