# Generated by Django 6.0.7 on 2026-08-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('order_confirmation', 'Order Confirmation'), ('shipping_update', 'Shipping Update'), ('delivery_update', 'Delivery Update'), ('payment_update', 'Payment Update'), ('password_reset', 'Password Reset'), ('promo', 'Promotional'), ('admin_alert', 'Admin Alert')], max_length=30),
        ),
    ]
