# Generated by Django 6.0.7 on 2026-07-18 00:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_name', models.CharField(default='Cut & Cult', max_length=120)),
                ('tagline', models.CharField(blank=True, default='Building a culture. One cut at a time.', max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('currency_symbol', models.CharField(default='$', max_length=3)),
                ('shipping_flat_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, default=Decimal('200.00'), max_digits=10, null=True)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('order_email_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'store settings',
            },
        ),
    ]
