# Generated by Django 6.0.7 on 2026-07-18 07:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='currency_symbol',
            field=models.CharField(default='₹', max_length=3),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='free_shipping_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('1999.00'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='shipping_flat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('99.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5),
        ),
    ]
