# Generated by Django 6.0.7 on 2026-07-18 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_mobile_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\+91[6-9]\\d{9}$', 'Enter a valid Indian mobile number (10 digits, starting with 6-9).')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, db_index=True, max_length=16, validators=[django.core.validators.RegexValidator('^\\+91[6-9]\\d{9}$', 'Enter a valid Indian mobile number (10 digits, starting with 6-9).')]),
        ),
    ]
